version: '3.9'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file: ./.env
    environment:
      - DB_ROOT_PASS=${DB_ROOT_PASS}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - inception_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: ./.env
    environment:
      - DB_HOST=mariadb
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASS}
      - WORDPRESS_DB_NAME=${DB_NAME}
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception_network

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file: ./.env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/diahmed/data/wordpress
      o: bind
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/diahmed/data/mariadb_data
      o: bind