services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_net
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_net
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wp_data:/var/www/html
      - ./requirements/nginx/certs:/etc/nginx/certs
    networks:
      - inception_net
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/diahmed/data/db
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/diahmed/data/website
      o: bind

networks:
  inception_net: